import os

HTML = """
<html>
<head>
<title>DPP System – UI Index</title>
<style>
body {{ font-family: Arial; background:#f4f6f8; }}
.card {{ max-width:700px; margin:30px auto; background:white; padding:20px; border-radius:8px; }}
a {{ display:block; margin:10px 0; font-size:16px; }}
</style>
</head>
<body>
<div class="card">
<h2>📦 Digital Product Passport – UI Index</h2>

<a href="{public}">🟢 Buyer Public Passport</a>
<a href="{verify}">🔍 Buyer Verify Page</a>
<a href="{analytics}">📊 Company Analytics Dashboard</a>

<p style="font-size:12px;color:#666">
These pages are auto-generated by the system.
</p>
</div>
</body>
</html>
"""

def generate_ui_index(company_id, product_id, version):
    path = "data/ui_index.html"

    html = HTML.format(
        public=f"data/public/{product_id}/v{version}.html",
        verify=f"data/verify/{product_id}-v{version}.html",
        analytics=f"data/dashboard_analytics/{company_id}.html"
    )

    with open(path, "w") as f:
        f.write(html)

    return path
